# -*- coding: utf-8 -*-
"""House_Price_Prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQ2ic6Gli0sn8_IEBIA1IDv5y-Ol2t9l
"""

!pip install --upgrade scikit-learn==1.4.0

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Housing.csv')
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

print(X)

print(y)

from sklearn.preprocessing import LabelEncoder
for i in range(X[:, 3:].shape[1]):
    le = LabelEncoder()
    X[:, 3 + i] = le.fit_transform(X[:, 3 + i])

print(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

X_train

X_test

y_train

y_test

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

X_test

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

input_data = [[3180,4,2,2,1,0,0,0,0,0,0,1]]
scaled_input = sc.transform(input_data)
prediction = regressor.predict(scaled_input)
print(prediction)

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

import pickle

filename = 'new_model.pkl'
pickle.dump(regressor, open(filename, 'wb'))

loaded_model = pickle.load(open('new_model.pkl', 'rb'))

input_data = [[3180,4,2,2,1,0,0,0,0,0,0,1]]
scaled_input = sc.transform(input_data)
prediction = loaded_model.predict(scaled_input)
print(prediction)